<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>active_hook_captain</name>
  <version>0.0.1</version>
  <description>Teleop + mavros bridge captain interface for an ardusub rov</description>
  <maintainer email="aliulvi4103@hotmail.com">Ali Ulvi Kaplan</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>mavros_msgs</depend>
  <depend>active_hook_msgs</depend>

  <exec_depend>joy</exec_depend>
  <exec_depend>gscam</exec_depend>
   <!-- Add this back in once mavros is back in apt! And remove the temp install in activehook-humble.yaml -->
  <!-- <exec_depend>mavros</exec_depend>-->


  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
